### PR TITLE
[ci skip] DP-9454: Update openjdk

### PR DESCRIPTION
**Pull request by vinnybod**

### CODE REVIEW

**Comment by gracechensd** [comment]
would we be able to pint merge the one from #248 here?

**Review by gracechensd — APPROVED** [review]

**Comment by vinnybod** [comment]
I thought you can't specify an upper bound for pint merge? In that case it would try to merge up through 6.0.x->7.2.x which we wouldn't want. Unless I have that wrong.

**Comment by gracechensd** [comment]
oh yeah sorry i mean git merge, i think it would probably be like a manual `git merge` 5.4 -> 5.5,  `git merge -sours` 5.5 -> 6.0, then pint merge can handle the rest

**Comment by vinnybod** [comment]
yes, but branch protections 😞

**Comment by gracechensd** [comment]
understandable i have a bit of a bad habit with admin privileges on `common-docker` branches

**Pull request merged**
