### PR TITLE
ST-3962: update confluent-docker-utils to latest

### PR DESCRIPTION
**Pull request by niteshmor**
duplicate of #96 but to a different branch

### CODE REVIEW

**Comment by niteshmor** [comment]
The full list of related PRs as follows. I created a pull request to all branches to make sure build passes (there are subtle differences in the dockerfiles across versions).

#90 : 4.0.x  (upgrades from v0.0.25 of `confluent-docker-utils`)
#91 : 4.1.x  (upgrades from v0.0.27 of `confluent-docker-utils`)
#92 : 5.0.x  (duplicate of #91 but to a different branch)
#93 : 5.1.x  (duplicate of #91 but to a different branch)
#94 : 5.2.x  (duplicate of #91 but to a different branch)
#95 : 5.3.x  (duplicate of #91 but to a different branch)
#96 : 5.4.x  (upgrades to multiple docker files)
#97 : 5.5.x  (duplicate of #96 but to a different branch)
#98 : 6.0.x  (just a version upgrade needed. No docker file changes)
#89 : master (duplicate of #98 but to a different branch)

**Comment by xli1996** [comment]
I am not sure if we could just unpin pip version, to make the build stable, I think we might just want to pin pip to a new version. Actually I am not sure if they will continue update pip in python2.

**Comment by niteshmor** [comment]
> I am not sure if we could just unpin pip version, to make the build stable, I think we might just want to pin pip to a new version. Actually I am not sure if they will continue update pip in python2.

Good questions. Reason I unpinned it is to keep it consistent with the other Dockerfiles. We are not pinning versions anywhere else. Maybe a better idea is to use `apt-get install` for installing `pip` (as in the other docker file)?

**Comment by xli1996** [comment]
yeah, I think we do not pin the pip version in ubi image but only deb images(they use different version of python so pip2 and pip3), it might just because the old deb images pinned pip version. But yeah, I do not have other reason to object it except it make the build more rebuildable.

**Comment by niteshmor** [comment]
Valid concern. If I recall correctly, Jan 2021 is when they will stop supporting pip2

**Pull request merged**
