### PR TITLE
DP-8414: Add default log4j property 

### PR DESCRIPTION
**Pull request by xjin-Confluent**
- Introduce default config at INFO level for utility command. 

https://confluentinc.atlassian.net/browse/DP-6627?focusedCommentId=736032

### CODE REVIEW

**Review by gracechensd — COMMENTED** [review]
I saw in an [older PR here](https://github.com/confluentinc/common-docker/pull/169) that Andrew had concerns about adding the log4j.properties file to the classpath, hence why the [BasicConfigurator.configure exists](https://github.com/confluentinc/common-docker/pull/170)

One alternative I got working and validated locally just now is just adding the line `org.apache.log4j.Logger.getRootLogger().setLevel(org.apache.log4j.Level.INFO);` above the line `BasicConfigurator.configure()`. Any thoughts on the different approaches?

**Comment by xjin-Confluent** [comment]
> I saw in an [older PR here](https://github.com/confluentinc/common-docker/pull/169) that Andrew had concerns about adding the log4j.properties file to the classpath, hence why the [BasicConfigurator.configure exists](https://github.com/confluentinc/common-docker/pull/170)
> 
> One alternative I got working and validated locally just now is just adding the line `org.apache.log4j.Logger.getRootLogger().setLevel(org.apache.log4j.Level.INFO);` above the line `BasicConfigurator.configure()`. Though I only saw that it removed the debug lines and don't know whether it negatively affected usual kafka/zookeeper/etc logging. Any thoughts on the different approaches?

Regarding https://github.com/confluentinc/common-docker/pull/169#issuecomment-988359646, it is because the log4j.propertity file not in the utility-belt folder. This PR tries to add the exact lo4j file and I verified locally that it will uses the newly added file. 

The goal is to (1) not log at debug level by default and (2) allow customer to config to debug level if needed. 

By setting this programmatically using `org.apache.log4j.Logger.getRootLogger().setLevel(org.apache.log4j.Level.INFO);`, can customers set it to DEBUG when needed?

**Review by gracechensd — APPROVED** [review]
OK that makes sense, I'm OK with proceeding with these changes then

**Comment by xjin-Confluent** [comment]
@gracechensd  Can you help me merge and pint it? I can then verify this behavior after the image is built.

**Comment by gracechensd** [comment]
Yes I can help with the pint merge portion

**Pull request merged**
