### PR TITLE
ST-3962: update confluent-docker-utils to latest

### PR DESCRIPTION
**Pull request by niteshmor**
duplicate of #98 but to a different branch

### CODE REVIEW

**Comment by niteshmor** [comment]
The full list of related PRs as follows. I created a pull request to all branches to make sure build passes (there are subtle differences in the dockerfiles across versions).

#90 : 4.0.x  (upgrades from v0.0.25 of `confluent-docker-utils`)
#91 : 4.1.x  (upgrades from v0.0.27 of `confluent-docker-utils`)
#92 : 5.0.x  (duplicate of #91 but to a different branch)
#93 : 5.1.x  (duplicate of #91 but to a different branch)
#94 : 5.2.x  (duplicate of #91 but to a different branch)
#95 : 5.3.x  (duplicate of #91 but to a different branch)
#96 : 5.4.x  (upgrades to multiple docker files)
#97 : 5.5.x  (duplicate of #96 but to a different branch)
#98 : 6.0.x  (just a version upgrade needed. No docker file changes)
#89 : master (duplicate of #98 but to a different branch)

**Comment by mohnishbasha** [comment]
i think we only need to target the oldest branch and use pint merge to propagate to the rest of the branches.

**Comment by xli1996** [comment]
> i think we only need to target the oldest branch and use pint merge to propagate to the rest of the branches.
> 
> @xli1996 any thoughts?

I think that might because there are multiple changes from different branches, and they might differ a little bit. Since pint merge does not support a merge until mode, so I think we either cherry pick to every branch and do `pint merge -s ours` or do multiple `pint merge`.

**Comment by niteshmor** [comment]
@mohnishbasha @xli1996 that makes sense, but will require a few batches of `pint merge` if we can even do it

- merge to 4.0.x
- merge to 4.1.x and then pint merge to 5.3.x
- merge to 5.4.x and then pint merge to 5.5.x
- merge to 6.0.x and then pint merge to master

**Comment by mohnishbasha** [comment]
> @mohnishbasha @xli1996 that makes sense, but will require a few batches of `pint merge` if we can even do it
> 
> * merge to 4.0.x
> * merge to 4.1.x and then pint merge to 5.0.x, 5.1.x, 5.2.x, and 5.3.x
> * merge to 5.4.x and then pint merge to 5.5.x
> * merge to 6.0.x and then pint merge to master

got it. thanks.

**Pull request merged**
