### PR TITLE
ST-4314: Install findutils to base image

### PR DESCRIPTION
**Pull request by elismaga**
Installing find in the ubi8 base docker image. This was in the debian images and is needed by users.

### CODE REVIEW

**Comment by andrewegel** [comment]
Is there a specific utility we ship in the image already that requires something from findutils, or is this a customer/user requesting that findutils be added to "help them"? If its the latter, then we should be telling them to build/derrive their own image. I've been told by some folks (Those that work with our Government Partners) that the UBI8 images are too large as it is for networks "on the edge" (as in limited bandwidth), so we should be striving to reduce sizes, not increase them.

**Comment by elismaga** [comment]
> Is there a specific utility we ship in the image already that requires something from findutils, or is this a customer/user requesting that findutils be added to "help them"? If its the latter, then we should be telling them to build/derrive their own image. I've been told by some folks (Those that work with our Government Partners) that the UBI8 images are too large as it is for networks "on the edge" (as in limited bandwidth), so we should be striving to reduce sizes, not increase them.

@andrewegel I believe since this request is coming from devx that it probably has to do with running demos and training. This package is only 528k
https://confluentinc.atlassian.net/browse/ST-4314

**Comment by andrewegel** [comment]
> I believe since this request is coming from devx that it probably has to do with running demos and training.

@javabrett & @ybyzek - I had a read over the related Jira, and my preference would be to augment the demo/docs that use `find` in our CP containers to use some other means of locating jars you're trying to demo. Either:

`ls /usr/share/java/*/jar-i-want.jar` or `ls /usr/share/java/*/* | grep jar-i-want`

As I already mentioned, I've seen reports from edge-network (places where bandwidth is very limited) users that these UBI8 images are already too large compared to the Debian ones, and we need to be "trimming the fat" where we can, this would be one of the first things to go, which is removing any unnecessary software to make the containers work. Contrast this to a recent change I made of adding `openssl` to the base-image: That was to make these containers work with Apache Mesos in the `mesos-setup.sh` (Code that we ship in the container).

Lets first consider trying to fix the demos/docs usage of `findutils` in docker images before we put this in.

**Comment by javabrett** [comment]
Some numbers that might be valuable in the analysis:

cp-server:6.0.x-latest : 1.24GB
ubi-minimal (8) : 142MB
ubi-minimal + find: 151MB (+9 MB)

**Comment by andrewegel** [comment]
As per internal discussions, this change will be dropped in leu of changing documentation to use basic utilities like `ls` for demo purposes.

**Pull request closed without merging**
